### ISSUE TITLE
Specify API version

### ISSUE THREAD

**Issue by HandyHat** [zeshan321/ActionHealth#14]
An API Version should be specified to stop legacy material support being initialised.

```
[Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[Server thread/WARN]: Legacy plugin ActionHealth v3.4.6 does not specify an api-version.
```

Using Action Health 3.4.6 and Paper 333

**Comment by zeshan321** [comment]
I'll look into this for the next release.

**Comment by zeshan321** [comment]
Resolved!

**Comment by zeshan321** [comment]
This ones more complicated. Looks like changing the API version breaks the TargetHelper class. So that will need to be updated also.
