### ISSUE TITLE
ActionHealthBar spams the console after updating Placeholder API

### ISSUE THREAD

**Issue by ellaira-ash** [zeshan321/ActionHealth#17]
Paper: 1.16.1
ActionHealthBar Version: 3.4.8
PlaceholderAPI Version: 2.10.7

Error: https://pastebin.com/zUNQvnRq

This error started spamming the console after I updated PlaceholderAPI.

**Comment by zeshan321** [comment]
Thanks for reporting! I'll look into this soon.

**Comment by zeshan321** [comment]
Should be good in 3.5.0.
