### ISSUE TITLE
Spam debug message

### ISSUE THREAD

**Issue by SaitDev** [zeshan321/ActionHealth#2]
Please remove your debug messages or add an option to disable it.
There are message about player's name every time health bar appears. It spams too much to console log

https://github.com/zeshan321/ActionHealth/blob/master/src/com/zeshanaslam/actionhealth/HealthUtil.java#L86

**Comment by zeshan321** [comment]
Fixed.

**Comment by SaitDev** [comment]
Thank for really fast and furious fix :) 👍
