### ISSUE TITLE
spam console

### ISSUE THREAD

**Issue by RIPISDRAD** [zeshan321/ActionHealth#24]
https://paste.walshy.dev/tiseviqeza
this is spamming like wow in my console=> it fricking crashed cause of it

**Comment by zeshan321** [comment]
Looks like your using 1.6 which isn't supported because the action bar does not exist in versions below 1.8.

**Comment by zeshan321** [comment]
What version are you using? Action health and MC version.

**Comment by RIPISDRAD** [comment]
i,m using 1.16.4
and i download it like 7month ago

**Comment by zeshan321** [comment]
Download the latest version on spigot.
