### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by S4IVin** [zeshan321/ActionHealth#26]
Hi, I'm an Italian, I found the ActionHealth plugin very useful for my server, so I translated it, I would like to share the translation of the mobs with you!

Name:
  - Bat = Pipistrello
  - Bee = Ape
  - Cat = Gatto
  - Cave Spider = Ragno delle caverne
  - Chicken = Gallina
  - Cod = Merluzzo
  - Cow = Mucca
  - Dolphin = Delfino
  - Donkey = Asino
  - Drowned = Annegato
  - Elder Guardian = Guardiano antico
  - Evoker = Evocatore
  - Fox = Volpe
  - Guardian = Guardiano
  - Horse = Cavallo
  - Husk = Zombi secco
  - Llama = Lama
  - Magma Cube = Cubo di magma
  - Mule = Mulo
  - Ocelot = Gattopardo
  - Parrot = Pappagallo
  - Pig = Maiale
  - Piglin Brute = Piglin Bruto
  - Pillager = Predone
  - Polar Bear = Orso polare
  - Pufferfish = Pesce palla
  - Rabbit = Coniglio
  - Ravanger = Devastatore
  - Salmon = Salmone
  - Sheep = Pecora
  - Silverfish = Pesciolino d'argento
  - Skeleton = Scheletro
  - Skeleton Horse = Cavallo scheletro
  - Spider = Ragno
  - Squid = Calamaro
  - Stray = Errante
  - Trader Llama = Lama del mercante
  - Tropical Fish = Pesce tropicale
  - Turtle = Tartaruga
  - Villager = Villico
  - Vindicator = Difensore
  - Wandering Trader = Mercante ambulante
  - Witch = Strega
  - Wither Skeleton = Scheletro wither
  - Wolf = Lupo
  - Zombie = Zombi
  - Zombie Horse = Cavallo zombi
  - Zombie Villager = Villico zombi
  - Zombified Piglin = Piglin zombificato

I hope it will be useful to many of the Italians who use this plugin!

**Comment by zeshan321** [comment]
Added! Thank you so much! Let me know if you'd like your server IP added to the list.

**Comment by S4IVin** [comment]
> Added! Thank you so much! Let me know if you'd like your server IP added to the list.

I'd love to! The server IP is mc.mine-core.it
