### ISSUE TITLE
placeholder {health} not correct for mob health, displays player health instead in actionbar

### ISSUE THREAD

**Issue by LcorpOfficial** [zeshan321/ActionHealth#29]
need a placeholder in config.yml example that relates to health of mob rather than player's heath. max_health works correctly for max health however.

installed papi, & mvdw, tried multiple placeholders relating to heath on both sides but cannot return mob current health with any.

**Comment by zeshan321** [comment]
Hey, are you asking for a placeholder that displays the attacking player (the player that gets the action health bar message) health?

**Comment by LcorpOfficial** [comment]
not quite; I'm looking for a placeholder that is assigned to the mob itself (for use with actionbar. currently {health} shows the health of yourself, the player. what you stated is what is currently delivered when using {health}.

**Comment by zeshan321** [comment]
The {health} placeholder shows the health of the mob the player attacks: https://youtu.be/DXonJ6PtX04?t=128

**Comment by zeshan321** [comment]
Most likely in your case you have another plugin interfering with ActionHealth or you just have a misunderstanding. ActionHealth was designed to show the health of the entity that the player attacks.

**Comment by LcorpOfficial** [comment]
perhaps an interference. I'm aware that {health} should show the entity that the player is attacking, however it shows the player's health instead. (the client that the actionbar is shown to)

**Comment by zeshan321** [comment]
Could you send your plugin list? Lets see if we can figure out what plugin is messing with it. Also, try a fresh server with only ActionHealth and see if it works as expected for you.

**Comment by LcorpOfficial** [comment]
will do when I can grab a spare day to do so :) here's plugin list.

https://pastebin.com/HvddLUHv

**Comment by n54b** [comment]
The problem is this 
![image](https://user-images.githubusercontent.com/12047619/121013926-b5442d80-c799-11eb-9bda-77c0674abc43.png)

**Comment by n54b** [comment]
if you disable MVdWPlaceholderAPI that working fine ! But i need that plugin for other plugin ^^ so can you found a solution ? =D

**Comment by zeshan321** [comment]
Add alterative placeholder for {health}, maybe {ahhealth}

**Comment by zeshan321** [comment]
@n54b thanks! In the latest version that will be out soon

https://github.com/zeshan321/ActionHealth/blob/6c0a799198df995bec0c4925ace57e0e3028b647/config.yml#L9
