### ISSUE TITLE
Not a Issue, just a Question...

### ISSUE THREAD

**Issue by Splixey** [zeshan321/ActionHealth#52]
Hello,
I was wondering if you guys support those hotbars that say like;

"10/10 ♥                                        Mana 10/10"

**Comment by zeshan321** [comment]
Are you looking for something similar to but with a heart after?
![image](https://user-images.githubusercontent.com/2091992/150698939-2b50a566-b278-4882-a430-8653ca849086.png)

**Comment by Splixey** [comment]
No I am so sorry for the confusion, I want it to look like this above your hotbar...
![unknown](https://user-images.githubusercontent.com/98282315/150699011-423923e9-1011-439c-93cb-e01d6527886c.png)

**Comment by Splixey** [comment]
I just can't find the actual plugin that does it, and I am not sure if you guys do this or?

**Comment by zeshan321** [comment]
Yes that should be possible with the modifying the configuration. As long as there is some placeholder hook for the mana part.
